project:
  type: website

website:
  page-navigation: true
  back-to-top-navigation: true
  title: "U.S. Greenhouse Gas Center - AMS 2023 Workshop"
  site-url: "https://us-ghg-center.github.io/ams-2023-workshop"
  repo-url: https://github.com/us-ghg-center/ams-2023-workshop
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By US GHG Center, 2022-2023"