project:
  type: website

website:
  page-navigation: true
  # back-to-top-navigation: true
  title: "AGENDA - AGU 2024 Pre-conference Workshop"
  site-url: "https://us-ghg-center.github.io/agu-2024-workshop"
  repo-url: https://github.com/us-ghg-center/agu-2024-workshop
  repo-actions: [edit, issue]

  navbar:
    search: false
    collapse: true
    left:
      #- text: Home
      #  file: index.md
      - text: SCHEDULE - US GHG Center at AGU 2024
        file: ghg-center-at-agu-2024.md
        # icon: team
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-By US GHG Center, 2024"

  sidebar:
    logo: "https://us-ghg-center.github.io/ghgc-docs/logo/ghgc-logo-light.svg"
    pinned: true
    align: center
    enabled: true
    ghg-center-at-agu-2024: false
    tools:
      - icon: globe-americas
        href: https://earth.gov/ghgcenter
        text: "US GHG Center Website"
      - icon: github
        href: https://github.com/us-ghg-center/agu-2024-workshop
        text: "Repository home"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.md
        text: Welcome
      #- href: agenda.md
      #  text: Workshop Agenda
      - href: https://github.com/nasa/Transform-to-Open-Science/blob/main/CODE_OF_CONDUCT.md
        text: Code of Conduct
      - href: prerequisites.md
        text: Prerequisites
   
      - section: Agenda
        contents:
          - text: Welcome
            href: sections/welcome/index.qmd
          - text: Overview of the U.S. Greenhouse Gas Center and the Science
            href: sections/overview-us-ghg-center/index.qmd
          - href: sections/activity-1/wetland.qmd
          - section: Activity Set 1 - Exploring Wetland Methane Emissions 
            href: sections/activity-1/index.qmd
            contents:
              - sections/activity-1/basics.qmd
              - sections/activity-1/lpjeosim-wetlandch4-grid-v1_User_Notebook.ipynb
              - sections/activity-1/qgis-setup.qmd
              - sections/activity-1/qgis-1.qmd
          - href: sections/activity-2/urban.qmd
          - section: Activity Set 2 - Exploring Urban Greenhouse Gas Emissions
            href: sections/activity-2/index.qmd
            contents:
              - sections/activity-2/gra2pes-ghg-monthgrid-v1_User_Notebook.ipynb
              - sections/activity-2/qgis-2.qmd
          - text: Closing
            href: sections/closing/index.qmd
      - href: team.md 
        text: Team             

format:
  html:
    grid:
      sidebar-width: 30vw
      body-width: 900px
    theme:
      light: [journal, style.scss]
    
    css: style.scss
    code-copy: true
    code-overflow: wrap
    # toc: true
    # # toc-depth: 3
    # toc-expand: true
